const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_CARTITEM_FROM_CART: "REMOVE_CARTITEM_FROM_CART",
  DECREASE_ITEM_BY_ONE: "DECREASE_ITEM_BY_ONE",
};

export default CartActionTypes;
